/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 *
 * Copyright:: (c) Kubris & Autotelik Media Ltd 2008
 * Author ::   Tom Statter
 * Date ::     28-Jan-2009, 14:44:21
 * License::   MIT ?
 * ConversionsTabPanel.java
 *
 */

package app.java.panels;

/**
 *
 * @author tom
 */
public class ConversionsTabPanel extends javax.swing.JPanel {

    /** Creates new form ConversionsTabPanel */
    public ConversionsTabPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    conversionsScrollPane = new javax.swing.JScrollPane();
    conversionsJXTable = new org.jdesktop.swingx.JXTable();
    conversionsSaveButton = new javax.swing.JButton();
    conversionsCreateButton = new javax.swing.JButton();

    conversionsJXTable.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null}
      },
      new String [] {
        "Name", "Mapping Reference", "Asset", "Source System", "Data Source", "Output System", "Title 7"
      }
    ) {
      boolean[] canEdit = new boolean [] {
        true, true, false, false, true, true, true
      };

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
      }
    });
    conversionsScrollPane.setViewportView(conversionsJXTable);

    conversionsSaveButton.setText("Save");

    conversionsCreateButton.setText("Create Conversion");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(conversionsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)
          .addComponent(conversionsCreateButton)
          .addComponent(conversionsSaveButton))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(conversionsCreateButton)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(conversionsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
        .addGap(11, 11, 11)
        .addComponent(conversionsSaveButton)
        .addContainerGap())
    );
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton conversionsCreateButton;
  public org.jdesktop.swingx.JXTable conversionsJXTable;
  private javax.swing.JButton conversionsSaveButton;
  private javax.swing.JScrollPane conversionsScrollPane;
  // End of variables declaration//GEN-END:variables

}
