/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * mappingTabPanel.java
 *
 * Created on 19-Jan-2009, 10:41:40
 */

package app.java.panels;

/**
 *
 * @author tom
 */
public class MappingTabPanel extends javax.swing.JPanel {

    /** Creates new form mappingTabPanel */
    public MappingTabPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mappingScrollPane = new javax.swing.JScrollPane();
        mappingTable = new org.jdesktop.swingx.JXTable();
        mappingSaveButtonTop = new javax.swing.JButton();
        mappingSourceComboBox = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        mappingSaveButtonBottom = new javax.swing.JButton();
        mappingPopulateButton = new javax.swing.JButton();
        mappingClearButton = new javax.swing.JButton();
        mappingClearAllButton = new javax.swing.JButton();
        mappingLoadButton = new javax.swing.JButton();

        mappingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Asset"
            }
        ));
        mappingScrollPane.setViewportView(mappingTable);

        mappingSaveButtonTop.setText("Save");

        jLabel7.setText("Mapping Source");

        mappingSaveButtonBottom.setText("Save");

        mappingPopulateButton.setText("Populate");
        mappingPopulateButton.setToolTipText("Pre populate the form with all mappable nodes");
        mappingPopulateButton.setMargin(new java.awt.Insets(2, 10, 2, 10));

        mappingClearButton.setText("Clear");
        mappingClearButton.setToolTipText("Clear all mappings from the form");
        mappingClearButton.setMargin(new java.awt.Insets(2, 10, 2, 10));

        mappingClearAllButton.setText("Clear All");
        mappingClearAllButton.setMargin(new java.awt.Insets(2, 10, 2, 10));

        mappingLoadButton.setText("Load");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mappingScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 681, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mappingSourceComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mappingPopulateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mappingClearButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mappingClearAllButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addComponent(mappingLoadButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mappingSaveButtonTop))
                    .addComponent(mappingSaveButtonBottom))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mappingSaveButtonTop)
                    .addComponent(jLabel7)
                    .addComponent(mappingSourceComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mappingPopulateButton)
                    .addComponent(mappingClearButton)
                    .addComponent(mappingLoadButton)
                    .addComponent(mappingClearAllButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mappingScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mappingSaveButtonBottom)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton mappingClearAllButton;
    private javax.swing.JButton mappingClearButton;
    private javax.swing.JButton mappingLoadButton;
    private javax.swing.JButton mappingPopulateButton;
    private javax.swing.JButton mappingSaveButtonBottom;
    private javax.swing.JButton mappingSaveButtonTop;
    private javax.swing.JScrollPane mappingScrollPane;
    private javax.swing.JComboBox mappingSourceComboBox;
    public org.jdesktop.swingx.JXTable mappingTable;
    // End of variables declaration//GEN-END:variables

}
