/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SchemasTabPanel.java
 *
 * Created on 03-May-2009, 10:42:12
 */

package app.java.panels;

/**
 *
 * @author Kuba
 */
public class SchemasTabPanel extends javax.swing.JPanel {

    /** Creates new form SchemasTabPanel */
    public SchemasTabPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    schemaToolBar = new javax.swing.JToolBar();
    schemasScrollPane = new javax.swing.JScrollPane();
    schemasTreeTable = new org.jdesktop.swingx.JXTreeTable();

    schemaToolBar.setRollover(true);

    schemasScrollPane.setViewportView(schemasTreeTable);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(schemasScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 774, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(10, 10, 10))
          .addComponent(schemaToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, 784, Short.MAX_VALUE)))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(schemaToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(schemasScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE)
        .addContainerGap())
    );
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JToolBar schemaToolBar;
  private javax.swing.JScrollPane schemasScrollPane;
  private org.jdesktop.swingx.JXTreeTable schemasTreeTable;
  // End of variables declaration//GEN-END:variables

}
